services:
  mysql:
    image: mysql:8.0
    container_name: assistente_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - assistente_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: assistente_app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      GROQ_API_KEY: ${GROQ_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "${APP_PORT:-5000}:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - assistente_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  assistente_network:
    driver: bridge